"""Embeds the web UI, the starter face templates and the fonts into the hub firmware.

PlatformIO runs this before building a hub environment (extra_scripts = pre:).
It gzips web/index.html and writes src/hub/web_assets.h, which web_server.cpp
includes. The header is regenerated only when an input is newer than it.
"""

import gzip
import json
from pathlib import Path

Import("env")  # noqa: F821  SCons provides this

root = Path(env.subst("$PROJECT_DIR"))
page = root / "web" / "index.html"
templates = sorted((root / "assets" / "templates").glob("*.json"))
fonts = sorted((root / "assets" / "fonts").glob("*.ttf"))
manifest = root / "assets" / "fonts" / "fonts.json"
script = root / "scripts" / "embed_web.py"
out = root / "src" / "hub" / "web_assets.h"


def c_array(name, data):
    lines = [f"static const uint8_t {name}[] = {{"]
    for i in range(0, len(data), 16):
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in data[i:i + 16]) + ",")
    lines.append("};")
    return "\n".join(lines)


def generate():
    if not page.exists():
        raise FileNotFoundError(f"web page missing: {page}")
    if not templates:
        raise FileNotFoundError(f"no templates in {root / 'assets' / 'templates'}")

    parts = [
        "// Generated by scripts/embed_web.py from web/ and assets/. Do not edit.",
        "#pragma once",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        "struct EmbeddedFile {",
        "    const char* name;",
        "    const uint8_t* data;",
        "    size_t size;",
        "};",
        "",
    ]

    html = page.read_bytes()
    gz = gzip.compress(html, compresslevel=9, mtime=0)
    parts.append(c_array("WEB_INDEX_GZ", gz))
    parts.append(f"static const size_t WEB_INDEX_GZ_LEN = {len(gz)};")
    parts.append("")

    for i, path in enumerate(templates):
        parts.append(c_array(f"WEB_TEMPLATE_{i}", path.read_bytes()))
    parts.append("static const EmbeddedFile WEB_TEMPLATES[] = {")
    for i, path in enumerate(templates):
        parts.append(f'    {{"{path.stem}", WEB_TEMPLATE_{i}, {path.stat().st_size}}},')
    parts.append("};")
    parts.append(f"static const size_t WEB_TEMPLATE_COUNT = {len(templates)};")
    parts.append("")

    for i, path in enumerate(fonts):
        parts.append(c_array(f"WEB_FONT_{i}", path.read_bytes()))
    if fonts:
        parts.append("static const EmbeddedFile WEB_FONTS[] = {")
        for i, path in enumerate(fonts):
            parts.append(f'    {{"{path.name}", WEB_FONT_{i}, {path.stat().st_size}}},')
        parts.append("};")
    else:
        parts.append("static const EmbeddedFile WEB_FONTS[1] = {};")
    parts.append(f"static const size_t WEB_FONT_COUNT = {len(fonts)};")
    parts.append("")

    # The font list the page shows, checked against the files actually embedded.
    entries = json.loads(manifest.read_text(encoding="utf-8"))
    keys = sorted(e["key"] for e in entries)
    files = sorted(p.stem for p in fonts)
    if keys != files:
        raise SystemExit(f"embed_web: fonts.json lists {keys} but the font files are {files}")
    compact = json.dumps(entries, separators=(",", ":")).encode("utf-8")
    parts.append(c_array("WEB_FONT_MANIFEST", compact))
    parts.append(f"static const size_t WEB_FONT_MANIFEST_LEN = {len(compact)};")
    parts.append("")

    out.write_text("\n".join(parts), encoding="utf-8")
    print(f"embed_web: index.html {len(html)} -> {len(gz)} bytes gzipped, "
          f"{len(templates)} templates, {len(fonts)} fonts")


inputs = [page, script, manifest] + templates + fonts
newest = max(p.stat().st_mtime for p in inputs if p.exists())
if not out.exists() or out.stat().st_mtime < newest:
    generate()
